### ISSUE TITLE
nocalhost dev deployment is missing privileged config

### ISSUE THREAD

**Issue by Poorunga** [nocalhost/nocalhost#1195]
**What happened**:

I am using nocalhost to debug kube-proxy.

I used the `Edit Manifest` to look at the yaml of kube-proxy, and there are privileges:

```
......
            containers:
                - command:
                    - /usr/local/bin/kube-proxy
                    - --config=/var/lib/kube-proxy/config.conf
                    - --hostname-override=$(NODE_NAME)
                    - --feature-gates=TopologyAwareHints=true
                  env:
                    - name: NODE_NAME
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: spec.nodeName
                  image: k8s.gcr.io/kube-proxy:v1.21.8
                  imagePullPolicy: IfNotPresent
                  name: kube-proxy
                  resources: {}
                  securityContext:
                    privileged: true        <--------------------------------- here!!!
......
```

However, the generated dev deployment, without privileged. I use the command `kubectl -n kube-system get deployment.apps/daemon-set-generated-deploy-kube-proxy -oyaml` to get dev deployment yaml:

(You cannot find privileged here)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-01-11T12:07:06Z"
  generation: 1
  labels:
    nocalhost.dev.workload.ignored: "true"
  name: daemon-set-generated-deploy-kube-proxy
  namespace: kube-system
  resourceVersion: "28962130"
  selfLink: /apis/apps/v1/namespaces/kube-system/deployments/daemon-set-generated-deploy-kube-proxy
  uid: f61d9b0a-1e6a-4d7e-a885-186617a1d452
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kube-proxy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
              - key: node-role.kubernetes.io/agent
                operator: DoesNotExist
      containers:
      - command:
        - /bin/sh
        - -c
        - tail -f /dev/null
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: nocalhost-docker.pkg.coding.net/nocalhost/dev-images/golang:zsh
        imagePullPolicy: Always
        name: nocalhost-dev
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kube-proxy
          name: kube-proxy
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /var/syncthing
          name: nocalhost-syncthing
          subPath: syncthing
        - mountPath: /var/syncthing/secret
          name: nocalhost-syncthing-secret
        - mountPath: /home/nocalhost-dev
          name: nocalhost-shared-volume
        workingDir: /home/nocalhost-dev
      - args:
        - rc-service sshd restart && unset STGUIADDRESS && cp /var/syncthing/secret/*
          /var/syncthing/ && /bin/entrypoint.sh && /bin/syncthing -home /var/syncthing
        command:
        - /bin/sh
        - -c
        image: nocalhost-docker.pkg.coding.net/nocalhost/public/nocalhost-sidecar:sshversion
        imagePullPolicy: Always
        name: nocalhost-sidecar
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/syncthing
          name: nocalhost-syncthing
          subPath: syncthing
        - mountPath: /var/syncthing/secret
          name: nocalhost-syncthing-secret
        - mountPath: /home/nocalhost-dev
          name: nocalhost-shared-volume
        workingDir: /home/nocalhost-dev
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-proxy
      serviceAccountName: kube-proxy
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: kube-proxy
        name: kube-proxy
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - emptyDir: {}
        name: nocalhost-syncthing
      - name: nocalhost-syncthing-secret
        secret:
          defaultMode: 448
          items:
          - key: config.xml
            mode: 448
            path: config.xml
          - key: cert.pem
            mode: 448
            path: cert.pem
          - key: key.pem
            mode: 448
            path: key.pem
          secretName: kube-proxy-daemonset-nocalhost-syncthing-secret
      - name: nocalhost-shared-volume
        persistentVolumeClaim:
          claimName: default.application-1641888119229698000
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-11T12:07:10Z"
    lastUpdateTime: "2022-01-11T12:07:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-11T12:07:06Z"
    lastUpdateTime: "2022-01-11T12:07:10Z"
    message: ReplicaSet "daemon-set-generated-deploy-kube-proxy-c5fb794bf" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

**This will make my dev container unprivileged and will not be able to create iptables rules!!!**

By the way, I manually adding privileges to dev deployment will solve this problem.

**Comment by wencaiwulue** [comment]
> daemon-set-generated

yes, you are right, this is a known issue, we already found it and will release a new version to fix it in this week, please keep on following :)

**Comment by yeya24** [comment]
What's the current status of this issue? @wencaiwulue

**Comment by wencaiwulue** [comment]
> What's the current status of this issue? @wencaiwulue

we already fixed issue, you can use latest version (v0.6.15) to have a try. looking forward your replys 👍

**Comment by Poorunga** [comment]
@wencaiwulue 

> we already fixed issue, you can use latest version (v0.6.15) to have a try. looking forward your replys

**I still can't find `securityContext: privileged: true`, in nocalhost auto-generated deployment yaml, and my nocalhost version is v0.6.15**

kube-proxy-gen-ae491616 is still not generated: `securityContext: privileged: true`, this is my deployment.apps/kube-proxy-gen-ae491616 yaml information:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-02-10T08:58:57Z"
  generation: 1
  labels:
    dev.nocalhost/workload-name: kube-proxy
    dev.nocalhost/workload-type: daemonset
    nocalhost.dev.workload.ignored: "true"
  name: kube-proxy-gen-ae491616
  namespace: kube-system
  resourceVersion: "2909171"
  selfLink: /apis/apps/v1/namespaces/kube-system/deployments/kube-proxy-gen-ae491616
  uid: 893437eb-04cf-43c8-9811-ab8e4a9834b0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kube-proxy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
              - key: node-role.kubernetes.io/agent
                operator: DoesNotExist
      containers:
      - command:
        - /bin/sh
        - -c
        - tail -f /dev/null
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: nocalhost-docker.pkg.coding.net/nocalhost/dev-images/golang:latest
        imagePullPolicy: Always
        name: nocalhost-dev
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kube-proxy
          name: kube-proxy
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /var/syncthing
          name: nocalhost-syncthing
          subPath: syncthing
        - mountPath: /var/syncthing/secret
          name: nocalhost-syncthing-secret
        - mountPath: /home/nocalhost-dev
          name: nocalhost-shared-volume
        workingDir: /home/nocalhost-dev
      - args:
        - rc-service sshd restart && unset STGUIADDRESS && cp /var/syncthing/secret/*
          /var/syncthing/ && /bin/entrypoint.sh && /bin/syncthing -home /var/syncthing
        command:
        - /bin/sh
        - -c
        image: nocalhost-docker.pkg.coding.net/nocalhost/public/nocalhost-sidecar:sshversion
        imagePullPolicy: Always
        name: nocalhost-sidecar
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/syncthing
          name: nocalhost-syncthing
          subPath: syncthing
        - mountPath: /var/syncthing/secret
          name: nocalhost-syncthing-secret
        - mountPath: /home/nocalhost-dev
          name: nocalhost-shared-volume
        workingDir: /home/nocalhost-dev
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-proxy
      serviceAccountName: kube-proxy
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: kube-proxy
        name: kube-proxy
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - emptyDir: {}
        name: nocalhost-syncthing
      - name: nocalhost-syncthing-secret
        secret:
          defaultMode: 448
          items:
          - key: config.xml
            mode: 448
            path: config.xml
          - key: cert.pem
            mode: 448
            path: cert.pem
          - key: key.pem
            mode: 448
            path: key.pem
          secretName: kube-proxy-daemonset-nocalhost-syncthing-secret
      - name: nocalhost-shared-volume
        persistentVolumeClaim:
          claimName: default.application-1644479899909405000
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-02-10T08:59:00Z"
    lastUpdateTime: "2022-02-10T08:59:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-02-10T08:58:57Z"
    lastUpdateTime: "2022-02-10T08:59:00Z"
    message: ReplicaSet "kube-proxy-gen-ae491616-5464b8ff4b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

**Comment by wencaiwulue** [comment]
we release a new version just now, you can have a try
